# Generated by Django 2.2 on 2023-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=200)),
                ('imgs', models.ImageField(upload_to='pics1')),
                ('des', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics1')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
